In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
    #numpy 기본은 행렬이다.
arr1.shape

(5,)

In [5]:
# 2차원 List
data2 = [
         [1,2,3,4],
         [5,6,7,8]
        ]
data2


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [9]:
# 0으로 구성된 1차원 배열 생성
    # page : 3 ,row : 5
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# 숫자 8로 구성된 3행 5열 배열 생성

np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [18]:
# 범위가 있는 배열 생성
    # numpy에서 정렬은 arange()
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# 데이터 타입 알아보기
arr1.dtype

dtype('float64')

In [22]:
arr3 = np.array([1,2,3,4,5], dtype= np.int64)
arr3.dtype

dtype('int64')

In [25]:
# data type을 변경하기
    # astype()
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [26]:
float_arr1

array([1., 2., 3., 4., 5.])

In [29]:
# 행렬 연산
arr1 = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
], dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [31]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [32]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [33]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [34]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [35]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [36]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [41]:
arr[5:9]

array([5, 6, 7, 8])

In [42]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [43]:
# slicing
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[8:]

array([12,  9])

### 2차원 배열


In [47]:
arr2d = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
    ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
arr2d.dtype

dtype('int64')

In [50]:
# 2번 행의 자료 출력

arr2d[2,:]

array([ 9, 10, 11, 12])

In [58]:
# 1에서 2번행의 자료 출력
arr2d[1,2]


7

In [63]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [59]:
# 0, 1열의 자료 출력
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [57]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [62]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0 부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일분포의 정수 난수

### Boolean Indexing

In [80]:
names = np.array(["Charles", "Kenny", "Hayoung", "Charles", "Hayoung", "Kenny", "Kenny"])
data = np.random.randn(7, 4)

In [81]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [83]:
# 7행으로 되어있다.
names.shape

(7,)

In [85]:
# 가우시안 난수 7행 4열
data

array([[-1.1522502 , -1.23996293,  1.4278929 , -0.84166709],
       [-0.71550379,  0.67002365,  0.56736922,  1.52082348],
       [ 0.62295949,  1.00903764,  0.8787698 , -1.08494649],
       [ 0.57453467, -0.33336388, -0.29528583,  0.39873399],
       [ 1.25183496, -0.2493469 , -0.00368804, -0.37447388],
       [-1.97441644, -0.07318447, -0.18672786,  0.06880407],
       [-0.55999007, -0.42254479,  2.88063661,  0.28143314]])

In [86]:
data.shape

(7, 4)

In [87]:
# Mask를 이용한 추출
    # true, false를 이용해서 추출하는 함수
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [89]:
# 0번 3번 행의 charles인 부분을 추출한다.
data[names == "Charles", :]

array([[-1.1522502 , -1.23996293,  1.4278929 , -0.84166709],
       [ 0.57453467, -0.33336388, -0.29528583,  0.39873399]])

In [90]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[-1.1522502 , -1.23996293,  1.4278929 , -0.84166709],
       [-0.71550379,  0.67002365,  0.56736922,  1.52082348],
       [ 0.57453467, -0.33336388, -0.29528583,  0.39873399],
       [-1.97441644, -0.07318447, -0.18672786,  0.06880407],
       [-0.55999007, -0.42254479,  2.88063661,  0.28143314]])

In [91]:
# data[:] = data
data

array([[-1.1522502 , -1.23996293,  1.4278929 , -0.84166709],
       [-0.71550379,  0.67002365,  0.56736922,  1.52082348],
       [ 0.62295949,  1.00903764,  0.8787698 , -1.08494649],
       [ 0.57453467, -0.33336388, -0.29528583,  0.39873399],
       [ 1.25183496, -0.2493469 , -0.00368804, -0.37447388],
       [-1.97441644, -0.07318447, -0.18672786,  0.06880407],
       [-0.55999007, -0.42254479,  2.88063661,  0.28143314]])

In [92]:
data[:,3]

array([-0.84166709,  1.52082348, -1.08494649,  0.39873399, -0.37447388,
        0.06880407,  0.28143314])

In [94]:
# data의 4번째 열 값중 0보다 작은 것의 mask 만들기

data[data[:, 3] < 0,:]

array([[-1.1522502 , -1.23996293,  1.4278929 , -0.84166709],
       [ 0.62295949,  1.00903764,  0.8787698 , -1.08494649],
       [ 1.25183496, -0.2493469 , -0.00368804, -0.37447388]])

In [98]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기

data[data[:, 3] < 0,:] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.71550379,  0.67002365,  0.56736922,  1.52082348],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.57453467, -0.33336388, -0.29528583,  0.39873399],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.97441644, -0.07318447, -0.18672786,  0.06880407],
       [-0.55999007, -0.42254479,  2.88063661,  0.28143314]])

In [99]:
# 정렬
arr = np.random.rand(8)
arr

array([0.71906215, 0.01123777, 0.1046798 , 0.42431722, 0.30646754,
       0.39788549, 0.35107085, 0.25585327])

In [100]:
# 오름차순 정렬
np.sort(arr)

array([0.01123777, 0.1046798 , 0.25585327, 0.30646754, 0.35107085,
       0.39788549, 0.42431722, 0.71906215])

In [101]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.71906215, 0.42431722, 0.39788549, 0.35107085, 0.30646754,
       0.25585327, 0.1046798 , 0.01123777])

In [102]:
arr = np.random.rand(5, 3)
arr

array([[0.30653456, 0.72426322, 0.68535264],
       [0.68013786, 0.24054271, 0.04676561],
       [0.07877124, 0.36868584, 0.88588908],
       [0.23535965, 0.28212865, 0.53681236],
       [0.69446025, 0.62009571, 0.98731159]])

In [103]:
# 0 : 열방향
np.sort(arr, axis=0)

array([[0.07877124, 0.24054271, 0.04676561],
       [0.23535965, 0.28212865, 0.53681236],
       [0.30653456, 0.36868584, 0.68535264],
       [0.68013786, 0.62009571, 0.88588908],
       [0.69446025, 0.72426322, 0.98731159]])

In [104]:
# 1 : 행방향
np.sort(arr, axis=1)

array([[0.30653456, 0.68535264, 0.72426322],
       [0.04676561, 0.24054271, 0.68013786],
       [0.07877124, 0.36868584, 0.88588908],
       [0.23535965, 0.28212865, 0.53681236],
       [0.62009571, 0.69446025, 0.98731159]])

In [107]:
# 1 : 행방향 , [:,::-1] : 내림차순
np.sort(arr, axis=1)[:,::-1]

array([[0.72426322, 0.68535264, 0.30653456],
       [0.68013786, 0.24054271, 0.04676561],
       [0.88588908, 0.36868584, 0.07877124],
       [0.53681236, 0.28212865, 0.23535965],
       [0.98731159, 0.69446025, 0.62009571]])

In [108]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [110]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
arr.shape

(8,)

In [112]:
# 2차원 배열로 변경
    # R에서 손글씨 인식같이 차원을 변경해주는 것
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2)) # (page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [128]:
# 2차원 배열을 1차원으로 변경
    # 딥러닝에서 차원 변경을 해서 학습하기때문에 reshape이 상당히 중요하다!
arr3 = arr1.reshape(-1, 1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [124]:
# 1차원으로 나온다
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [125]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])