In [1]:
# GPU 사용 설정
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = '1'

In [2]:
import pandas as pd
data= pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

- admit : 1합격,0불합격
- gre : 영어 성적
- gpa : 학점
- rank : 지원한 대학원 수준

### Preprocessing(전처리)

In [3]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [4]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른값으로 대체
# data.fillna(100)

In [5]:
# 결측치 확인
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [7]:
# 영어 점수의 최소값과 최대값
print("최대값 :",data['gre'].max())
print("최소값 :",data['gre'].min())

최대값 : 800.0
최소값 : 220.0


In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 425 entries, 0 to 425
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   admit   425 non-null    int64  
 1   gre     425 non-null    float64
 2   gpa     425 non-null    float64
 3   rank    425 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 16.6 KB


In [9]:
# Training Data
x = data[['gre', 'gpa','rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [10]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [11]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 입력층 3개. 출력은 1개

---
## Deep Learning Model 만들기

In [12]:
from tensorflow import keras

In [13]:
# 입력레이어를 주는데 층은 아니다?
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation='tanh')
output_layer = keras.layers.Dense(1, activation='sigmoid')

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [14]:
model = keras.Sequential(
    [input_layer,
    hidden_layer,
    output_layer]
)

Optimizer => Learning rate를 알맞게 조정해줌 ->(y - y^)
- adam
- adagrad
- adadelta
- rmsprop
- sgd  

loss : 손실함수
- binary_crossentropy : 분류 및 확률 예측 함수

metrics : 모델의 평가 기준


In [15]:
# 손실함수
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [16]:
# 학습 시키기
# 일반적인 fit은 못씀 pandas에 들어있어서 -> numpy로 바꿔줘야해
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
14/14 [==============================] - 1s 1ms/step - loss: 0.7047 - accuracy: 0.5224
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6777 - accuracy: 0.5906
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6694 - accuracy: 0.6118
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6691 - accuracy: 0.6235
Epoch 5/500


In [17]:
# hidden layer 가중치 값 출력
# 히든레이어에 AF를 주지 않으면 이값이 그대로 넘어감
hidden_layer.get_weights()[0]

array([[ 0.11696562,  0.08788735, -0.01973402,  0.13747373,  0.10296685,
        -0.12813085,  0.0358647 , -0.08246563, -0.01754894, -0.1230521 ,
         0.13119888,  0.01943052, -0.05694488, -0.14653614,  0.06125273,
         0.07465574,  0.10708675,  0.07713702,  0.03780134, -0.11577779,
         0.11005124, -0.0566422 , -0.04084698,  0.1418345 , -0.14095867,
        -0.05886115,  0.03398572,  0.1416153 , -0.01739352,  0.06557074,
         0.03315013, -0.05155016,  0.08273101, -0.01857948, -0.07254338,
        -0.12592703, -0.03596411, -0.09138288,  0.04547109, -0.12535575,
        -0.05345508, -0.02888061, -0.1181455 , -0.08107641,  0.15070233,
         0.03801386,  0.10866323,  0.05911814, -0.0052388 , -0.03700906,
         0.13244802,  0.06799501, -0.05683319, -0.08403858, -0.06692973,
         0.06137189,  0.04405101, -0.12587684, -0.03313854,  0.11115929,
        -0.06368411, -0.0221095 , -0.12155575,  0.06557105, -0.02031996,
        -0.05663403, -0.03765391,  0.06709814, -0.1

In [18]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [19]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[ 1.        ,  1.        , -0.99999946, ...,  1.        ,
        -1.        , -1.        ],
       [ 1.        ,  1.        , -1.        , ...,  1.        ,
        -1.        , -1.        ],
       [ 1.        ,  1.        , -1.        , ...,  1.        ,
        -1.        , -1.        ],
       ...,
       [ 1.        ,  1.        , -1.        , ...,  1.        ,
        -1.        , -1.        ],
       [ 1.        ,  1.        , -1.        , ...,  1.        ,
        -1.        , -1.        ],
       [ 1.        ,  1.        , -1.        , ...,  1.        ,
        -1.        , -1.        ]], dtype=float32)>